---
title: "Operation Logo"
output: github_document
---

https://www.r-spatial.org/r/2018/10/25/ggplot2-sf.html
https://stackoverflow.com/questions/43207947/whole-earth-polygon-for-world-map-in-ggplot2-and-sf

https://github.com/GuangchuangYu/hexSticker


```{r}
library(ggplot2)
library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(rgeos)
library(mapview)
library(lwgeom)
library(tidyverse)
library(hexSticker)
```

```{r}
ctrys50m <- ne_countries(scale = 50, type = "countries", returnclass = "sf") %>%
  select(iso_a3, iso_n3, admin)

world_coastlines <- ne_coastline(scale = 110, returnclass = 'sf')

world  <- st_cast(world_coastlines, 'MULTILINESTRING') %>%
  st_cast('LINESTRING', do_split=TRUE) %>%
  mutate(npts = npts(geometry, by_feature = TRUE)) %>%
  st_cast('POLYGON')


crs <- "+proj=laea +lat_0=10 +lon_0=-20"

sphere <- st_graticule(ndiscr = 10e4, margin = 10e-3) %>%
  st_transform(crs = crs) %>%
  st_convex_hull() %>%
  summarise(geometry = st_union(geometry))
```

```{r}
ggplot()  +
  geom_sf(data = world_coastlines) +
  coord_sf( crs= "+proj=ortho +lat_0=20 +lon_0=-30")
  
```



```{r}
globe_background <- ggplot()  +
  geom_sf(data = sphere, alpha = 0, color = 'white', size = 0.20) +
  geom_sf(data = ctrys50m, color = "white", alpha = 0, size = 0.09) +
  theme_void() + theme_transparent()

globe_background + theme(panel.background = element_rect(fill = 'steelblue'))
```




## Create Hex

```{r}
library(showtext)
## Loading Google fonts (http://www.google.com/fonts)
font_add_google("Roboto Slab")
```


```{r}
s <- sticker(globe_background,
    package = "tidygeocoder", p_size = 20, s_x = 1, s_y = .75, s_width = 1.4, s_height = 1.1, p_family = "Roboto Slab",
    h_color = 'dimgrey', h_fill = 'steelblue3', p_color = 'white', filename = here::here("man/figures/tidygeocoder_hex.png"))

plot(s)
#filename ="logo.png"
```

