---
title: "Regression Testing"
---

Regression testing. Make sure to cover geocodio, google, and iq since those methods aren't covered in the vignettes.

```{r setup}
library(tibble)
library(dplyr)
library(knitr)
library(tidygeocoder)

sample1 <- tibble(address = c('11 Wall St New York, NY', NA, '',
    '1600 Pennsylvania Ave NW Washington, DC', '11 Wall St New York, NY', 
    'Toronto, Canada'))

sample2 <- tibble(street = c('1600 Pennsylvania Ave NW', '11 Wall Street', ''), 
  city = c('Washington', 'New York', 'Nashville'), state = c('DC', 'NY', 'TN'))
```


```{r, error = TRUE}
# test batch limit
sample1 %>%
  geocode(address, verbose = F, batch_limit = 1)
```


```{r}
louisville_check <- louisville %>% 
  geocode(street = street, city = city, state = state, postalcode = zip, verbose = TRUE, full_results = TRUE) %>%
  mutate(lat_diff = lat - latitude, long_diff = long - longitude) %>%
  select(lat_diff, long_diff, everything())

louisville_check
```

```{r}
louisville_geocodio <- louisville %>% 
  geocode(street = street, city = city, state = state, postalcode = zip, verbose = TRUE, method = 'geocodio', full_results = TRUE) %>%
   mutate(lat_diff = lat - latitude, long_diff = long - longitude) %>%
  select(lat_diff, long_diff, everything())

louisville_geocodio
```



```{r}
geo(street='1449 ST JAMES CT', city =  'Louisville', state = 'KY', postalcode =  '40208', full_results = TRUE, verbose = T)	
```


```{r}
geocode_google1 <- sample1 %>% 
  geocode(address = address, method = 'google', full_results = TRUE, verbose = TRUE)
geocode_google1
```

```{r}
geocode_google1_notflat <- sample1 %>% slice(1,2,4,5) %>%
  geocode(address = address, method = 'google', full_results = TRUE, verbose = TRUE, flatten = FALSE, unique_only = TRUE)
geocode_google1_notflat
```


```{r}
cascade_r1 <- geo(c('', NA, sample_addresses$addr, NA, ''), method = 'cascade', cascade_order = c('census', 'geocodio'), verbose = T)
cascade_r1
```


```{r}
gc1 <- geocode_geocodio1 <- sample1 %>% 
  geocode(address = address, method = 'geocodio', verbose = TRUE)
gc1
```

```{r}
iq1 <- geocode_geocodio1 <- sample1 %>% 
  geocode(address = address, method = 'iq', full_results = TRUE, verbose = TRUE, unique_only = TRUE)
iq1
```



```{r}
gc_c1 <- geo(method = 'geocodio', street = c('1600 Pennsylvania Ave NW', '11 Wall Street', ''), 
  city = c('Washington', 'New York', 'Nashville'), state = c('DC', 'NY', 'TN'), verbose = TRUE, full_results = TRUE)
gc_c1
```

```{r}
iq_c1 <- sample2 %>% 
  geocode(street = street, city = city, state = state, method = 'iq', verbose = TRUE, full_results = TRUE)
iq_c1
```


```{r, error = TRUE}
geo('blank address', method = 'makeanerror')
```


Check geocodio error catching

```{r, error = TRUE}
geo(' -----', method ='geocodio')
```

# Check mapbox

```{r}

louisville_mapbox <- louisville %>%
  slice(1:10) %>%
  geocode(
    address = street,
    method = 'mapbox',
    full_results = TRUE,
    custom_query = list(
      proximity = paste0(louisville[1, c("longitude", "latitude")], 
                         collapse = ","))) %>%
  mutate(lat_diff = lat - latitude,
         long_diff = long - longitude) %>%
  select(lat_diff, long_diff, everything())

louisville_mapbox
```


```{r}
geocode_mapbox1 <- sample1 %>%
  mutate(addr = address) %>%
  select(-address) %>%
  geocode(
    address = addr,
    method = 'mapbox',
    full_results = TRUE,
    verbose = TRUE
  )
geocode_mapbox1
```


```{r}

geocode_mapbox2 <- sample1 %>%
  geocode(
    address = address,
    method = 'mapbox',
    full_results = FALSE,
    verbose = TRUE
  )
geocode_mapbox2
```

## Check mapbox error catching

```{r}
geo('Testing',
    method = 'mapbox',
    custom_query = list(country = "ERROR"))
```
# Check here

```{r}

louisville_here <- louisville %>%
  geocode(
    address = street,
    method = 'here',
    full_results = TRUE,
    custom_query = list(at = paste0(louisville[1, c("latitude", "longitude")],
                                    collapse = ","))
  ) %>%
  mutate(lat_diff = lat - latitude,
         long_diff = long - longitude) %>%
  select(lat_diff, long_diff, everything())

louisville_here
```


```{r}
geocode_here1 <- sample1 %>%
  geocode(
    address = address,
    method = 'here',
    full_results = TRUE
  )
geocode_here1
```